### ISSUE TITLE
Getting error while running `up`

### ISSUE THREAD

**Issue by killerdejavu** [pullpreview/action#36]
```
/app/lib/pull_preview/up.rb:51:in `run': undefined method `bundle_id' for nil:NilClass (NoMethodError)
	from /app/lib/pull_preview/github_sync.rb:111:in `sync!'
	from /app/lib/pull_preview/github_sync.rb:26:in `run'
	from /app/bin/pullpreview:79:in `<main>'
```

**Comment by crohr** [comment]
Hello, which version of the action are you using?

**Comment by crohr** [comment]
This should have been fixed in the latest v5 tag quite a while ago, so closing since you haven't replied. Please let me know if you still experience the issue with `pullpreview/action@v5`.
